/**
 * Teacher Report PDF Template
 * 
 * Generates a professional teacher performance report PDF.
 */

import { PDFDocument, rgb, StandardFonts } from "pdf-lib";
import type { TeacherReportData, PdfGenerationResult } from "../types";

export async function generateTeacherReport(
  data: TeacherReportData
): Promise<PdfGenerationResult> {
  try {
    const pdfDoc = await PDFDocument.create();
    const page = pdfDoc.addPage([595, 842]); // A4 size

    const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
    const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

    const { width, height } = page.getSize();
    const margin = 50;
    let yPos = height - margin;

    // Header
    page.drawText("Tibyan Academy", {
      x: margin,
      y: yPos,
      size: 24,
      font: fontBold,
      color: rgb(0.1, 0.3, 0.6),
    });
    yPos -= 40;

    page.drawText("Teacher Performance Report", {
      x: margin,
      y: yPos,
      size: 18,
      font: fontBold,
      color: rgb(0.2, 0.2, 0.2),
    });
    yPos -= 40;

    // Horizontal line
    page.drawLine({
      start: { x: margin, y: yPos },
      end: { x: width - margin, y: yPos },
      thickness: 1,
      color: rgb(0.7, 0.7, 0.7),
    });
    yPos -= 30;

    // Report details
    const drawField = (label: string, value: string) => {
      page.drawText(label, {
        x: margin,
        y: yPos,
        size: 12,
        font: fontBold,
        color: rgb(0.3, 0.3, 0.3),
      });
      page.drawText(value, {
        x: margin + 150,
        y: yPos,
        size: 12,
        font,
        color: rgb(0.1, 0.1, 0.1),
      });
      yPos -= 25;
    };

    drawField("Teacher Name:", data.teacherName);
    if (data.teacherNameEn) {
      drawField("Name (English):", data.teacherNameEn);
    }
    drawField("Report Date:", data.reportDate);
    drawField("Course:", data.courseName);
    if (data.courseNameEn) {
      drawField("Course (English):", data.courseNameEn);
    }

    yPos -= 20;

    // Statistics section
    page.drawText("Statistics", {
      x: margin,
      y: yPos,
      size: 14,
      font: fontBold,
      color: rgb(0.1, 0.3, 0.6),
    });
    yPos -= 25;

    drawField("Total Students:", String(data.totalStudents));
    drawField("Completed:", String(data.completedStudents));
    
    const completionRate = data.totalStudents > 0 
      ? Math.round((data.completedStudents / data.totalStudents) * 100) 
      : 0;
    drawField("Completion Rate:", `${completionRate}%`);

    if (data.averageScore !== undefined) {
      drawField("Average Score:", `${data.averageScore}%`);
    }

    if (data.notes) {
      yPos -= 20;
      page.drawText("Notes:", {
        x: margin,
        y: yPos,
        size: 12,
        font: fontBold,
        color: rgb(0.3, 0.3, 0.3),
      });
      yPos -= 20;

      // Word wrap notes
      const maxWidth = width - 2 * margin;
      const words = data.notes.split(" ");
      let line = "";
      
      for (const word of words) {
        const testLine = line + (line ? " " : "") + word;
        const textWidth = font.widthOfTextAtSize(testLine, 11);
        
        if (textWidth > maxWidth) {
          page.drawText(line, {
            x: margin,
            y: yPos,
            size: 11,
            font,
            color: rgb(0.2, 0.2, 0.2),
          });
          yPos -= 16;
          line = word;
        } else {
          line = testLine;
        }
      }
      
      if (line) {
        page.drawText(line, {
          x: margin,
          y: yPos,
          size: 11,
          font,
          color: rgb(0.2, 0.2, 0.2),
        });
      }
    }

    // Footer
    page.drawText("Generated by Tibyan Academy • Zyphon AI", {
      x: margin,
      y: 30,
      size: 9,
      font,
      color: rgb(0.5, 0.5, 0.5),
    });

    const pdfBuffer = await pdfDoc.save();
    const filename = `teacher-report-${Date.now()}.pdf`;

    return {
      success: true,
      pdfBuffer,
      filename,
    };
  } catch (error) {
    console.error("[PDF] Teacher report generation error:", error);
    return {
      success: false,
      error: error instanceof Error ? error.message : "Failed to generate PDF",
    };
  }
}
