/**
 * SVG Generator Type Definitions
 * 
 * Types for the local SVG image generation system.
 * DesignSpec is generated by Groq and validated with Zod.
 * 
 * NOTE: This module is maintained for backward compatibility.
 * New code should use @/lib/zyphon/design-engine instead.
 */

import { z } from "zod";

// Re-export from design-engine for gradual migration
export type { LegacyDesignSpec } from "../design-engine/types";

// ============================================
// Zod Schemas for validation
// ============================================

export const CanvasSchema = z.object({
  w: z.number().min(256).max(2048).default(1024),
  h: z.number().min(256).max(2048).default(1024),
  bg: z.string().regex(/^#[0-9A-Fa-f]{6}$/).default("#000000"),
});

export const TextSchema = z.object({
  value: z.string().min(1).max(100),
  strokeWidth: z.number().min(1).max(50).default(10),
  geometryStyle: z.enum(["kufic-block", "kufic-rounded", "angular", "geometric"]).default("kufic-block"),
  centered: z.boolean().default(true),
  color: z.string().regex(/^#[0-9A-Fa-f]{6}$/).optional(),
  scale: z.number().min(0.5).max(3).default(1),
});

export const IslamicPatternSchema = z.object({
  enabled: z.boolean().default(true),
  opacity: z.number().min(0).max(1).default(0.08),
  tile: z.enum(["8-point-star", "6-point-star", "hexagonal", "octagonal"]).default("8-point-star"),
  scale: z.number().min(0.5).max(3).default(1),
  color: z.string().regex(/^#[0-9A-Fa-f]{6}$/).optional(),
});

export const CircuitPatternSchema = z.object({
  enabled: z.boolean().default(true),
  opacity: z.number().min(0).max(1).default(0.18),
  density: z.number().min(0.1).max(1).default(0.35),
  color: z.string().regex(/^#[0-9A-Fa-f]{6}$/).optional(),
  nodeRadius: z.number().min(1).max(10).default(3),
});

export const PatternsSchema = z.object({
  islamic: IslamicPatternSchema.optional(),
  circuit: CircuitPatternSchema.optional(),
});

export const AccentSchema = z.object({
  color: z.string().regex(/^#[0-9A-Fa-f]{6}$/).default("#00A86B"),
  lineWeight: z.number().min(1).max(20).default(3),
  glow: z.number().min(0).max(1).default(0),
});

export const DesignSpecSchema = z.object({
  canvas: CanvasSchema,
  text: TextSchema,
  patterns: PatternsSchema.optional(),
  accent: AccentSchema.optional(),
  seed: z.number().int().min(0).max(999999999).default(0),
});

// ============================================
// TypeScript Types (inferred from schemas)
// ============================================

export type Canvas = z.infer<typeof CanvasSchema>;
export type TextSpec = z.infer<typeof TextSchema>;
export type IslamicPattern = z.infer<typeof IslamicPatternSchema>;
export type CircuitPattern = z.infer<typeof CircuitPatternSchema>;
export type Patterns = z.infer<typeof PatternsSchema>;
export type Accent = z.infer<typeof AccentSchema>;
export type DesignSpec = z.infer<typeof DesignSpecSchema>;

// ============================================
// Request Schema for API
// ============================================

export const DesignRequestSchema = z.object({
  brandTextAr: z.string().min(1).max(50).default("تِبيان"),
  style: z.enum(["modern-kufic", "classic-kufic", "geometric", "angular"]).default("modern-kufic"),
  mood: z.enum(["minimal-premium", "vibrant", "traditional", "tech"]).default("minimal-premium"),
  accent: z.enum(["emerald", "gold", "sapphire", "ruby", "purple"]).default("emerald"),
  background: z.enum(["black", "dark-gray", "navy", "dark-green"]).default("black"),
});

export type DesignRequest = z.infer<typeof DesignRequestSchema>;

// ============================================
// Accent color map
// ============================================

export const ACCENT_COLORS: Record<string, string> = {
  emerald: "#00A86B",
  gold: "#FFD700",
  sapphire: "#0F52BA",
  ruby: "#E0115F",
  purple: "#9B30FF",
};

export const BACKGROUND_COLORS: Record<string, string> = {
  black: "#000000",
  "dark-gray": "#1A1A1A",
  navy: "#0A0A2E",
  "dark-green": "#0A1F0A",
};

// ============================================
// Design Engine Integration
// ============================================

// Export adapter functions for migration
export {
  fromLegacySpec,
  toLegacySpec,
  renderLegacy,
  safeRenderLegacy,
} from "../design-engine/adapter";

